using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace MovieDatabase.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class RemovedAutoGeneratedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 4);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 5);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 6);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 7);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 8);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 9);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 10);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 11);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 12);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 13);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 14);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 15);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 16);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 17);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 18);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 19);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 20);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 21);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 22);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 23);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 24);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 25);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 26);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 27);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 28);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 29);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 30);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 31);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 32);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 33);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 34);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 35);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 36);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 37);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 38);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 39);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 40);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 41);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 42);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 43);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 44);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 45);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 46);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 47);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 48);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 49);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 50);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 51);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 52);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 53);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 54);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 55);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 56);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 57);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 58);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 59);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 60);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 61);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 62);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 63);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 64);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 65);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 66);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 67);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 68);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 69);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 70);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 71);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 72);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 73);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 74);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 75);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 76);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 77);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 78);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 79);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 80);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 81);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 82);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 83);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 84);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 85);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 86);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 87);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 88);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 89);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 90);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 91);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 92);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 93);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 94);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 95);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 96);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 97);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 98);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 99);

            migrationBuilder.DeleteData(
                table: "Movies",
                keyColumn: "Id",
                keyValue: 100);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Movies",
                columns: new[] { "Id", "Director", "Genre", "Rating", "Title", "Year" },
                values: new object[,]
                {
                    { 1, "Brandon Aufderhar", 10, 5.7000130069683852, "Auto Loan Account extend paradigms", 2017 },
                    { 2, "Vernice Osinski", 1, 90.185274778216822, "bandwidth Handcrafted Rubber Chicken communities", 1945 },
                    { 3, "Ottis DuBuque", 5, 46.247155141828259, "Horizontal Accountability Generic", 1976 },
                    { 4, "Mollie Dietrich", 2, 86.172294844095745, "Savings Account Executive Chief", 1947 },
                    { 5, "Henry Kemmer", 0, 46.213798334251251, "blue violet Cotton", 1928 },
                    { 6, "David Tromp", 21, 83.521155550162646, "Lead Honduras Rustic Steel Computer", 1953 },
                    { 7, "Zula Ebert", 10, 65.789654492539313, "local area network Platinum Ergonomic Fresh Bacon", 1989 },
                    { 8, "Caitlyn Beer", 18, 33.413215492684365, "Investment Account deposit orchid", 1951 },
                    { 9, "Piper Stiedemann", 12, 75.485306266379482, "hack Representative lavender", 2005 },
                    { 10, "Susie Harber", 17, 42.459751702638201, "Kentucky input Clothing, Outdoors & Health", 1984 },
                    { 11, "Angelina Metz", 0, 90.653550866085979, "Assistant Turnpike interface", 1993 },
                    { 12, "Selina Beer", 3, 2.0582340811053812, "blue Port Developer", 1941 },
                    { 13, "Eli Quigley", 17, 66.026363058234523, "Frozen Concrete metrics", 1962 },
                    { 14, "Ludie Muller", 20, 28.240530810353125, "Automated Electronics, Garden & Industrial Tasty", 1972 },
                    { 15, "Lora Effertz", 15, 29.44166664532445, "bus Checking Account FTP", 1910 },
                    { 16, "Thalia Feest", 18, 22.530755987057884, "deposit compressing supply-chains", 1977 },
                    { 17, "Vilma Wehner", 21, 70.064174769361827, "Stravenue matrix array", 2016 },
                    { 18, "Brandt Jacobson", 17, 34.192096166874144, "Frozen Markets Berkshire", 1943 },
                    { 19, "Chad Conn", 17, 49.723180622399966, "facilitate heuristic Metrics", 1940 },
                    { 20, "Beverly Schamberger", 2, 25.859627648553818, "Berkshire bricks-and-clicks Mali", 1903 },
                    { 21, "Vesta Lindgren", 8, 11.155811920421854, "Groves payment Delaware", 1963 },
                    { 22, "Scarlett Hoeger", 3, 87.550417981478319, "Regional Customer Bedfordshire", 1965 },
                    { 23, "Bertha Rippin", 16, 92.970352124701435, "wireless Intelligent Intelligent", 1920 },
                    { 24, "Lambert Littel", 5, 23.698351619698034, "Yemeni Rial Delaware niches", 1924 },
                    { 25, "Elisabeth Dickens", 13, 39.741665584905014, "leverage deposit EXE", 1920 },
                    { 26, "Joey Marks", 20, 31.13035772589755, "utilize Squares human-resource", 1939 },
                    { 27, "Alvera Tromp", 9, 10.71145459956676, "Outdoors & Jewelery Tasty Fundamental", 1972 },
                    { 28, "Leta Johns", 9, 33.762965006120368, "Puerto Rico GB Branding", 1908 },
                    { 29, "Mervin Macejkovic", 19, 69.670290696195366, "Borders Functionality payment", 1901 },
                    { 30, "Cleve Ondricka", 21, 23.712681681522994, "Manager B2C connecting", 1936 },
                    { 31, "Arnold Kemmer", 11, 65.945867669221428, "dot-com invoice Buckinghamshire", 1986 },
                    { 32, "Marilou Kerluke", 13, 45.584675142482823, "Associate vertical Avon", 1931 },
                    { 33, "Sincere Wisoky", 1, 84.353462775696869, "Bedfordshire Ergonomic Steel Shirt grow", 1907 },
                    { 34, "Millie Wuckert", 5, 50.932482507042295, "Bedfordshire Burgs maroon", 2020 },
                    { 35, "Nikita Rowe", 3, 12.445390554247016, "Chile deposit Fresh", 2019 },
                    { 36, "Monty Armstrong", 0, 79.725634361946291, "Curve Automotive & Health visionary", 1928 },
                    { 37, "Einar Nitzsche", 2, 45.724656321698845, "Metal directional e-business", 1919 },
                    { 38, "Wava Kuvalis", 20, 65.240034278006576, "RSS Street Virtual", 1993 },
                    { 39, "Dandre Larkin", 9, 29.983776855217315, "web-readiness Cuban Peso Convertible actuating", 1971 },
                    { 40, "Domenick Hackett", 10, 65.768371865683761, "payment Chief bandwidth", 1996 },
                    { 41, "Iliana Hirthe", 21, 26.026751929216474, "Handmade Rubber Shirt info-mediaries Brook", 1992 },
                    { 42, "Lesly Schmeler", 18, 75.44894308413393, "orchid Bedfordshire District", 1950 },
                    { 43, "Jakob Sanford", 5, 70.462869155039073, "e-commerce structure navigating", 1907 },
                    { 44, "Nakia Carroll", 14, 96.151257203119485, "Product Jewelery gold", 1937 },
                    { 45, "Antonette Stoltenberg", 16, 69.09190337180415, "protocol wireless Implementation", 1986 },
                    { 46, "Ryleigh Willms", 5, 24.690855393534772, "concept XML neural", 1940 },
                    { 47, "Ursula Murphy", 6, 17.988874540610322, "Unbranded driver payment", 1964 },
                    { 48, "Sharon Pacocha", 5, 22.679021512691445, "parsing Course Technician", 1914 },
                    { 49, "Adelbert Ankunding", 4, 50.117570825583904, "Administrator definition Lane", 1952 },
                    { 50, "Effie Rogahn", 6, 7.8523398069437755, "National Berkshire composite", 2016 },
                    { 51, "Rhoda Bernhard", 12, 24.164345978830916, "Guernsey Avon silver", 1979 },
                    { 52, "Jarvis Beier", 10, 41.824522885302585, "Pike Awesome Beauty", 1944 },
                    { 53, "Breanna Leannon", 2, 94.919404501792314, "Maine Analyst Frozen", 1950 },
                    { 54, "Kamille Harvey", 12, 81.752571103714018, "plug-and-play Analyst Manor", 1968 },
                    { 55, "Clay Welch", 17, 29.450353718069632, "Oman green Credit Card Account", 2010 },
                    { 56, "Frederic Ward", 8, 18.369108046977235, "cross-platform Books, Electronics & Beauty turquoise", 1971 },
                    { 57, "Haleigh Kling", 5, 28.896777617702764, "Facilitator Metal Credit Card Account", 1978 },
                    { 58, "Frederic Monahan", 15, 10.494731797757828, "deposit multi-byte Estates", 1914 },
                    { 59, "Abdullah Pouros", 9, 69.134581373676767, "indigo Motorway collaborative", 1922 },
                    { 60, "Taya Bradtke", 18, 30.393230355214428, "deploy brand Savings Account", 1952 },
                    { 61, "Lydia Balistreri", 18, 97.580948946586119, "indexing Ports Investment Account", 1948 },
                    { 62, "Harley Feil", 14, 20.587299008741255, "Berkshire Yen Zambian Kwacha", 2021 },
                    { 63, "Margot McCullough", 11, 75.269389049511375, "Coordinator Investment Account clear-thinking", 1927 },
                    { 64, "Lonny Blanda", 1, 82.227843696681617, "parsing input tan", 1908 },
                    { 65, "Aidan Kreiger", 13, 62.909238349507113, "Credit Card Account Pennsylvania Representative", 1982 },
                    { 66, "Anibal Leuschke", 6, 36.229028056921479, "Plastic schemas reintermediate", 1993 },
                    { 67, "Jarrod Frami", 19, 27.50115628811718, "yellow payment parsing", 1923 },
                    { 68, "Junior Klein", 0, 90.901878540230669, "connecting SMS Cayman Islands", 1995 },
                    { 69, "Jeramy King", 6, 4.2473184232661669, "Ergonomic Mobility maroon", 1908 },
                    { 70, "Jovani Hessel", 3, 91.099608165164696, "Operations Egyptian Pound markets", 1910 },
                    { 71, "Nicole Trantow", 2, 95.265166056952637, "Practical Soft Soap indigo Incredible", 1949 },
                    { 72, "Ceasar Lehner", 1, 56.059802780474321, "Forward Square Facilitator", 1904 },
                    { 73, "Wilfred Carroll", 14, 4.7391898972820918, "Planner Coordinator Cambridgeshire", 2018 },
                    { 74, "Eli Dietrich", 11, 74.431165290225849, "Arkansas Junctions Small Fresh Towels", 2016 },
                    { 75, "Toy Douglas", 10, 94.678001485118585, "AI Licensed Fresh Chair invoice", 1989 },
                    { 76, "Beth Paucek", 12, 62.619826711648564, "Central Plastic solid state", 1959 },
                    { 77, "Kaela Graham", 9, 97.545998858479336, "online Music, Computers & Clothing Fantastic", 1987 },
                    { 78, "Blanche Walter", 14, 50.314819381965947, "e-markets CSS West Virginia", 1913 },
                    { 79, "Lukas Abshire", 21, 42.869565780757789, "Chief Legacy CSS", 1929 },
                    { 80, "Kathryn Hickle", 17, 65.367847442256036, "enable Alaska Planner", 1977 },
                    { 81, "Eliza Haag", 4, 20.789575987133311, "payment Coves Sleek Metal Table", 1991 },
                    { 82, "Earl Gusikowski", 4, 43.534913566901913, "Product front-end THX", 1948 },
                    { 83, "Emiliano Berge", 8, 27.631074820362112, "leverage Concrete Saudi Riyal", 1953 },
                    { 84, "Erwin Romaguera", 10, 13.209366191634221, "open architecture next generation Saint Pierre and Miquelon", 1903 },
                    { 85, "Travon Fadel", 21, 67.105776879359496, "Loaf Paraguay Sharable", 1947 },
                    { 86, "Alvera Dickinson", 15, 68.027613125526727, "Toys & Health withdrawal Dale", 1927 },
                    { 87, "Lexus Hessel", 0, 98.037560447989833, "Gorgeous Rubber Table platforms Sleek", 1952 },
                    { 88, "Brice Tremblay", 9, 70.192190745187943, "Plains full-range Solutions", 1936 },
                    { 89, "Amir Feest", 14, 79.343761434648528, "Jewelery & Garden Intelligent Wooden Soap technologies", 2009 },
                    { 90, "Lucy Dibbert", 4, 25.991899735457547, "payment Ergonomic Rubber Cheese Integration", 1908 },
                    { 91, "Enrique Swaniawski", 12, 6.7312934887209241, "maroon Ergonomic Fresh Chicken Maine", 1984 },
                    { 92, "Thaddeus Kozey", 8, 18.79001258686873, "content-based Mississippi Human", 1964 },
                    { 93, "Dorothea Anderson", 1, 8.7089023661700899, "Arkansas pixel National", 1959 },
                    { 94, "Francisca Rosenbaum", 4, 60.053313107097871, "engage ROI SAS", 1955 },
                    { 95, "Braden Rolfson", 20, 87.723958345639886, "enterprise Inlet Implementation", 2015 },
                    { 96, "Orrin Parker", 17, 46.074621277080055, "Total Intelligent Metal Chicken actuating", 1995 },
                    { 97, "Kelley Upton", 17, 19.926816450982276, "Oregon mindshare Rubber", 1900 },
                    { 98, "Grace Moen", 2, 64.613521504757372, "California generate transmitter", 1912 },
                    { 99, "Alec Marquardt", 17, 92.671759779611591, "Underpass strategic Assistant", 1990 },
                    { 100, "Alberta Schmeler", 15, 36.737206996201834, "system leverage Auto Loan Account", 1975 }
                });
        }
    }
}
