// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDatabase.Persistence;

#nullable disable

namespace MovieDatabase.Persistence.Migrations
{
    [DbContext(typeof(MovieDBContext))]
    partial class MovieDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Bertrand Schoen",
                            Genre = 19,
                            Title = "Massachusetts Berkshire card",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            Director = "Uriel Langosh",
                            Genre = 6,
                            Title = "Parkways Consultant Ergonomic Cotton Chips",
                            Year = 2005
                        },
                        new
                        {
                            Id = 3,
                            Director = "Derrick Gorczany",
                            Genre = 7,
                            Title = "Rustic Engineer Neck",
                            Year = 1988
                        },
                        new
                        {
                            Id = 4,
                            Director = "Javonte Nitzsche",
                            Genre = 18,
                            Title = "Cedi Creative dedicated",
                            Year = 1970
                        },
                        new
                        {
                            Id = 5,
                            Director = "Michale Keebler",
                            Genre = 6,
                            Title = "holistic Handcrafted Fresh Bike supply-chains",
                            Year = 2005
                        },
                        new
                        {
                            Id = 6,
                            Director = "Dorothea Padberg",
                            Genre = 18,
                            Title = "Analyst Awesome Metal Bike Intranet",
                            Year = 1948
                        },
                        new
                        {
                            Id = 7,
                            Director = "Missouri Cassin",
                            Genre = 14,
                            Title = "Australia Identity models",
                            Year = 2004
                        },
                        new
                        {
                            Id = 8,
                            Director = "Kylie White",
                            Genre = 20,
                            Title = "dynamic Global parse",
                            Year = 1914
                        },
                        new
                        {
                            Id = 9,
                            Director = "Maryjane Dach",
                            Genre = 1,
                            Title = "Rustic Mandatory Silver",
                            Year = 2000
                        },
                        new
                        {
                            Id = 10,
                            Director = "Cynthia Becker",
                            Genre = 10,
                            Title = "orchid Awesome Frozen Gloves wireless",
                            Year = 1964
                        },
                        new
                        {
                            Id = 11,
                            Director = "Anjali Rice",
                            Genre = 12,
                            Title = "e-business Applications Executive",
                            Year = 1952
                        },
                        new
                        {
                            Id = 12,
                            Director = "Alfredo Price",
                            Genre = 3,
                            Title = "El Salvador Colon Beauty, Games & Games frictionless",
                            Year = 1983
                        },
                        new
                        {
                            Id = 13,
                            Director = "Ottilie Cummerata",
                            Genre = 4,
                            Title = "haptic transmitter array",
                            Year = 2019
                        },
                        new
                        {
                            Id = 14,
                            Director = "Elwyn Stroman",
                            Genre = 6,
                            Title = "next-generation Ranch AI",
                            Year = 2001
                        },
                        new
                        {
                            Id = 15,
                            Director = "Amelia Pouros",
                            Genre = 12,
                            Title = "monitor Persevering Green",
                            Year = 1945
                        },
                        new
                        {
                            Id = 16,
                            Director = "Layla Schmeler",
                            Genre = 7,
                            Title = "Secured Awesome Cambridgeshire",
                            Year = 1902
                        },
                        new
                        {
                            Id = 17,
                            Director = "Lois Koss",
                            Genre = 20,
                            Title = "Intelligent Auto Loan Account bottom-line",
                            Year = 1926
                        },
                        new
                        {
                            Id = 18,
                            Director = "Alfred O'Conner",
                            Genre = 11,
                            Title = "Investor monitor Incredible Plastic Towels",
                            Year = 1918
                        },
                        new
                        {
                            Id = 19,
                            Director = "Johan Collins",
                            Genre = 0,
                            Title = "Ranch Well neural",
                            Year = 1959
                        },
                        new
                        {
                            Id = 20,
                            Director = "Reinhold Cruickshank",
                            Genre = 4,
                            Title = "Algerian Dinar input Hungary",
                            Year = 1999
                        },
                        new
                        {
                            Id = 21,
                            Director = "Jaquelin West",
                            Genre = 2,
                            Title = "architect Shoes, Health & Toys open-source",
                            Year = 1932
                        },
                        new
                        {
                            Id = 22,
                            Director = "Aditya Dooley",
                            Genre = 17,
                            Title = "24/7 solution strategize",
                            Year = 1902
                        },
                        new
                        {
                            Id = 23,
                            Director = "Dewayne Johnson",
                            Genre = 15,
                            Title = "Ergonomic dynamic South Dakota",
                            Year = 1913
                        },
                        new
                        {
                            Id = 24,
                            Director = "Maddison Stamm",
                            Genre = 18,
                            Title = "analyzing Profound best-of-breed",
                            Year = 2006
                        },
                        new
                        {
                            Id = 25,
                            Director = "Orland Turner",
                            Genre = 7,
                            Title = "Ergonomic Expanded mint green",
                            Year = 1917
                        },
                        new
                        {
                            Id = 26,
                            Director = "Akeem Becker",
                            Genre = 0,
                            Title = "Nepalese Rupee 4th generation Grocery, Grocery & Electronics",
                            Year = 1909
                        },
                        new
                        {
                            Id = 27,
                            Director = "Sim Sanford",
                            Genre = 15,
                            Title = "Representative Sleek Frozen Tuna Maine",
                            Year = 1927
                        },
                        new
                        {
                            Id = 28,
                            Director = "Celia Emmerich",
                            Genre = 9,
                            Title = "recontextualize South Africa Awesome Soft Cheese",
                            Year = 1928
                        },
                        new
                        {
                            Id = 29,
                            Director = "Dolly Kuphal",
                            Genre = 4,
                            Title = "optimal orchid override",
                            Year = 1980
                        },
                        new
                        {
                            Id = 30,
                            Director = "Iva Wintheiser",
                            Genre = 16,
                            Title = "bandwidth port HDD",
                            Year = 1926
                        },
                        new
                        {
                            Id = 31,
                            Director = "Cullen Erdman",
                            Genre = 15,
                            Title = "Coordinator Unbranded Ferry",
                            Year = 1978
                        },
                        new
                        {
                            Id = 32,
                            Director = "Marilyne Runolfsson",
                            Genre = 21,
                            Title = "paradigm parse Gorgeous Soft Computer",
                            Year = 1993
                        },
                        new
                        {
                            Id = 33,
                            Director = "Santa Rohan",
                            Genre = 16,
                            Title = "sensor withdrawal withdrawal",
                            Year = 1962
                        },
                        new
                        {
                            Id = 34,
                            Director = "Cecelia Monahan",
                            Genre = 12,
                            Title = "Delaware deposit Concrete",
                            Year = 2005
                        },
                        new
                        {
                            Id = 35,
                            Director = "Francisco Hilpert",
                            Genre = 17,
                            Title = "Money Market Account portals best-of-breed",
                            Year = 1997
                        },
                        new
                        {
                            Id = 36,
                            Director = "Jacques McDermott",
                            Genre = 11,
                            Title = "Borders global Forward",
                            Year = 2002
                        },
                        new
                        {
                            Id = 37,
                            Director = "Cierra Kuphal",
                            Genre = 3,
                            Title = "artificial intelligence Crossroad Ergonomic Soft Tuna",
                            Year = 1901
                        },
                        new
                        {
                            Id = 38,
                            Director = "Amie White",
                            Genre = 7,
                            Title = "Pines Romania SMTP",
                            Year = 1921
                        },
                        new
                        {
                            Id = 39,
                            Director = "Dejah Runolfsson",
                            Genre = 10,
                            Title = "Nepal Innovative French Polynesia",
                            Year = 1912
                        },
                        new
                        {
                            Id = 40,
                            Director = "Coy Schneider",
                            Genre = 13,
                            Title = "Checking Account red Rhode Island",
                            Year = 1904
                        },
                        new
                        {
                            Id = 41,
                            Director = "Chadd Sawayn",
                            Genre = 2,
                            Title = "deliverables Falkland Islands (Malvinas) Bedfordshire",
                            Year = 2008
                        },
                        new
                        {
                            Id = 42,
                            Director = "Mae Schiller",
                            Genre = 19,
                            Title = "Vermont relationships TCP",
                            Year = 1908
                        },
                        new
                        {
                            Id = 43,
                            Director = "Alicia Boehm",
                            Genre = 7,
                            Title = "feed content SSL",
                            Year = 2018
                        },
                        new
                        {
                            Id = 44,
                            Director = "Wilfrid Kshlerin",
                            Genre = 1,
                            Title = "Via Gibraltar Pound navigate",
                            Year = 1903
                        },
                        new
                        {
                            Id = 45,
                            Director = "Alanna Erdman",
                            Genre = 20,
                            Title = "cross-platform Program Qatari Rial",
                            Year = 2018
                        },
                        new
                        {
                            Id = 46,
                            Director = "Yesenia Hessel",
                            Genre = 6,
                            Title = "approach Auto Loan Account Som",
                            Year = 1927
                        },
                        new
                        {
                            Id = 47,
                            Director = "Anastasia Abernathy",
                            Genre = 11,
                            Title = "Auto Loan Account Steel Data",
                            Year = 1989
                        },
                        new
                        {
                            Id = 48,
                            Director = "Stephany Greenfelder",
                            Genre = 15,
                            Title = "Computers, Outdoors & Beauty transform Lead",
                            Year = 1988
                        },
                        new
                        {
                            Id = 49,
                            Director = "Brando Fadel",
                            Genre = 3,
                            Title = "CSS Lead holistic",
                            Year = 1987
                        },
                        new
                        {
                            Id = 50,
                            Director = "Edna Dietrich",
                            Genre = 20,
                            Title = "users Licensed Wooden Gloves composite",
                            Year = 1900
                        },
                        new
                        {
                            Id = 51,
                            Director = "Quincy Spencer",
                            Genre = 21,
                            Title = "Plastic parsing e-commerce",
                            Year = 1988
                        },
                        new
                        {
                            Id = 52,
                            Director = "Makenna Barrows",
                            Genre = 4,
                            Title = "turn-key Avon Automotive",
                            Year = 1938
                        },
                        new
                        {
                            Id = 53,
                            Director = "Arvid Turner",
                            Genre = 14,
                            Title = "Product calculate Green",
                            Year = 2018
                        },
                        new
                        {
                            Id = 54,
                            Director = "Patsy Roob",
                            Genre = 2,
                            Title = "facilitate Incredible Granite Keyboard Agent",
                            Year = 2003
                        },
                        new
                        {
                            Id = 55,
                            Director = "Elizabeth O'Kon",
                            Genre = 12,
                            Title = "Paradigm Steel auxiliary",
                            Year = 1921
                        },
                        new
                        {
                            Id = 56,
                            Director = "Friedrich Kuhic",
                            Genre = 1,
                            Title = "Configuration Inverse indexing",
                            Year = 1997
                        },
                        new
                        {
                            Id = 57,
                            Director = "Reagan Beatty",
                            Genre = 21,
                            Title = "Borders ADP Bedfordshire",
                            Year = 1901
                        },
                        new
                        {
                            Id = 58,
                            Director = "Cynthia Grant",
                            Genre = 19,
                            Title = "Auto Loan Account Minnesota Curve",
                            Year = 1989
                        },
                        new
                        {
                            Id = 59,
                            Director = "Ezequiel Pagac",
                            Genre = 14,
                            Title = "Director solutions holistic",
                            Year = 1952
                        },
                        new
                        {
                            Id = 60,
                            Director = "Geo Turner",
                            Genre = 4,
                            Title = "Future-proofed copying viral",
                            Year = 1944
                        },
                        new
                        {
                            Id = 61,
                            Director = "Lura Langosh",
                            Genre = 0,
                            Title = "Handcrafted Soft Mouse Sleek Steel Hat Directives",
                            Year = 1957
                        },
                        new
                        {
                            Id = 62,
                            Director = "Karlee Wolff",
                            Genre = 12,
                            Title = "Music, Kids & Grocery Qatar Frozen",
                            Year = 2001
                        },
                        new
                        {
                            Id = 63,
                            Director = "Magnolia Murazik",
                            Genre = 1,
                            Title = "world-class Sleek Parkways",
                            Year = 1958
                        },
                        new
                        {
                            Id = 64,
                            Director = "Loma Prosacco",
                            Genre = 2,
                            Title = "connecting attitude THX",
                            Year = 1970
                        },
                        new
                        {
                            Id = 65,
                            Director = "Mckayla Dooley",
                            Genre = 18,
                            Title = "Somali Shilling Producer Movies, Computers & Outdoors",
                            Year = 1920
                        },
                        new
                        {
                            Id = 66,
                            Director = "Aurelio Padberg",
                            Genre = 5,
                            Title = "Integration Tennessee Facilitator",
                            Year = 1910
                        },
                        new
                        {
                            Id = 67,
                            Director = "Jazmyne Grimes",
                            Genre = 9,
                            Title = "hack 24 hour Generic Soft Bacon",
                            Year = 1962
                        },
                        new
                        {
                            Id = 68,
                            Director = "Lexus Rippin",
                            Genre = 16,
                            Title = "payment array invoice",
                            Year = 1945
                        },
                        new
                        {
                            Id = 69,
                            Director = "Justina Kub",
                            Genre = 2,
                            Title = "Qatari Rial HDD generate",
                            Year = 2004
                        },
                        new
                        {
                            Id = 70,
                            Director = "Myriam Goodwin",
                            Genre = 4,
                            Title = "black Home Loan Account redundant",
                            Year = 1972
                        },
                        new
                        {
                            Id = 71,
                            Director = "Berry Botsford",
                            Genre = 1,
                            Title = "Lari Rubber pink",
                            Year = 1967
                        },
                        new
                        {
                            Id = 72,
                            Director = "Hassan Klocko",
                            Genre = 20,
                            Title = "Euro Plains Green",
                            Year = 1918
                        },
                        new
                        {
                            Id = 73,
                            Director = "Gloria Halvorson",
                            Genre = 18,
                            Title = "Mongolia Auto Loan Account Throughway",
                            Year = 2013
                        },
                        new
                        {
                            Id = 74,
                            Director = "Dayton Kutch",
                            Genre = 0,
                            Title = "Cuban Peso Future internet solution",
                            Year = 1948
                        },
                        new
                        {
                            Id = 75,
                            Director = "Aimee Strosin",
                            Genre = 9,
                            Title = "Colombia Marketing utilize",
                            Year = 1962
                        },
                        new
                        {
                            Id = 76,
                            Director = "Arielle Prohaska",
                            Genre = 6,
                            Title = "Ports Puerto Rico impactful",
                            Year = 1965
                        },
                        new
                        {
                            Id = 77,
                            Director = "Luisa Rosenbaum",
                            Genre = 6,
                            Title = "Investment Account New York productivity",
                            Year = 1923
                        },
                        new
                        {
                            Id = 78,
                            Director = "Fabiola Barton",
                            Genre = 7,
                            Title = "array Small Concrete Shoes Frozen",
                            Year = 1985
                        },
                        new
                        {
                            Id = 79,
                            Director = "Asa Murray",
                            Genre = 19,
                            Title = "Toys, Beauty & Grocery Ergonomic generate",
                            Year = 1980
                        },
                        new
                        {
                            Id = 80,
                            Director = "Adaline Batz",
                            Genre = 9,
                            Title = "primary Practical Granite Salad Monaco",
                            Year = 1915
                        },
                        new
                        {
                            Id = 81,
                            Director = "Meredith Reinger",
                            Genre = 14,
                            Title = "Customer backing up Practical",
                            Year = 1925
                        },
                        new
                        {
                            Id = 82,
                            Director = "Hiram Lueilwitz",
                            Genre = 16,
                            Title = "monitor Belize Dollar French Polynesia",
                            Year = 2008
                        },
                        new
                        {
                            Id = 83,
                            Director = "Sierra Walsh",
                            Genre = 0,
                            Title = "payment CFA Franc BCEAO capacitor",
                            Year = 1927
                        },
                        new
                        {
                            Id = 84,
                            Director = "Buck Lindgren",
                            Genre = 13,
                            Title = "olive benchmark Producer",
                            Year = 1935
                        },
                        new
                        {
                            Id = 85,
                            Director = "Marge Davis",
                            Genre = 14,
                            Title = "Orchestrator Trafficway Garden, Toys & Toys",
                            Year = 1964
                        },
                        new
                        {
                            Id = 86,
                            Director = "Rodolfo Prosacco",
                            Genre = 19,
                            Title = "Sports & Electronics Sleek Rubber Computer Zloty",
                            Year = 2006
                        },
                        new
                        {
                            Id = 87,
                            Director = "Ezra Mante",
                            Genre = 13,
                            Title = "Kiribati parsing transmitting",
                            Year = 1996
                        },
                        new
                        {
                            Id = 88,
                            Director = "German Beer",
                            Genre = 15,
                            Title = "Yemeni Rial Operations Ridge",
                            Year = 1953
                        },
                        new
                        {
                            Id = 89,
                            Director = "Clement Crooks",
                            Genre = 0,
                            Title = "Credit Card Account Global Usability",
                            Year = 1957
                        },
                        new
                        {
                            Id = 90,
                            Director = "Lucinda Legros",
                            Genre = 6,
                            Title = "Mozambique Avon Tunnel",
                            Year = 1918
                        },
                        new
                        {
                            Id = 91,
                            Director = "General Ernser",
                            Genre = 7,
                            Title = "Investor Lead Investment Account",
                            Year = 1972
                        },
                        new
                        {
                            Id = 92,
                            Director = "Gennaro Nader",
                            Genre = 13,
                            Title = "gold Forward black",
                            Year = 1987
                        },
                        new
                        {
                            Id = 93,
                            Director = "Chauncey Herzog",
                            Genre = 16,
                            Title = "Seychelles Rupee Passage Refined Cotton Bike",
                            Year = 1956
                        },
                        new
                        {
                            Id = 94,
                            Director = "Ludie Ankunding",
                            Genre = 10,
                            Title = "dot-com Sleek Lead",
                            Year = 1956
                        },
                        new
                        {
                            Id = 95,
                            Director = "Jermaine Mueller",
                            Genre = 1,
                            Title = "Toys Handmade SDD",
                            Year = 2010
                        },
                        new
                        {
                            Id = 96,
                            Director = "Dolly Smitham",
                            Genre = 5,
                            Title = "bypassing quantifying Internal",
                            Year = 1910
                        },
                        new
                        {
                            Id = 97,
                            Director = "Conner Steuber",
                            Genre = 4,
                            Title = "SSL Forest auxiliary",
                            Year = 2004
                        },
                        new
                        {
                            Id = 98,
                            Director = "Eleazar Quitzon",
                            Genre = 2,
                            Title = "Jewelery Tools, Baby & Movies Checking Account",
                            Year = 1981
                        },
                        new
                        {
                            Id = 99,
                            Director = "Cortez Swaniawski",
                            Genre = 17,
                            Title = "solutions enhance compress",
                            Year = 1904
                        },
                        new
                        {
                            Id = 100,
                            Director = "Titus Doyle",
                            Genre = 11,
                            Title = "Kids, Movies & Outdoors Strategist feed",
                            Year = 1939
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
